### ISSUE TITLE
Add support for custom emotes

### ISSUE THREAD

**Issue by zet4** [cucmberium/Flantter.MilkyWay#128]
Fediverse servers such as Mastodon and Pleroma have support for adding custom emojis, currently the app does not support this and thus all the custom emojis just look like :text:.

For example this status: https://mstdn.io/users/zeta/statuses/99893603217308279
Is OK on **Pleroma**: https://stuff.zeta.pm/up/PowderbluePositivePacificparrotlet
And is OK on **Mastodon**: https://stuff.zeta.pm/up/WobblyWelllitIggypops
But is NOT OK on **Flantter**: https://stuff.zeta.pm/up/AmusingAdolescentAlligatorgar

**Comment by cucmberium** [comment]
I implemented a feature of showing custom emojis before.
But that version has a bug that client is terminated abnormally when enabling the setting "Enable tweet text selection".
The cause is unknown and I couldn't fix it. (See branch [feature/custom_emoji](https://github.com/cucmberium/Flantter.MilkyWay/tree/feature/custom_emoji))
I plan to implement about custom emoji using another approach.
Please wait a moment for next release.

**Comment by cucmberium** [comment]
reference : #124 #125

**Comment by LordMicroMan** [comment]
New user for Flantter. Don't have "Enable tweet text selection" on but still can't use custom mastodon emoji. Any news on the update?
